import {mkdir,writeFile,cp,rm} from 'node:fs/promises';
import path from 'node:path';
import {content,affiliate,sources} from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=['payments','vip','sports'];
const legalRoutes=['privacy','terms','responsible-play'];
const url=(lang,kind='home')=>(lang==='fr'?'/fr':'')+(kind==='home'?'/':'/'+kind);
const arrow='<span aria-hidden="true">↗</span>';
const logo='<span class="brand-mark" aria-hidden="true">t.</span><span>treolympus<span class="brand-dot">.</span></span>';
const cta=t=>`<a class="btn" href="${affiliate}" data-affiliate rel="sponsored noopener">${t.cta}${arrow}</a>`;
function shell(lang,kind,body,outbound=false){
 const t=content[lang],other=lang==='en'?'fr':'en';
 const title=kind==='home'?'Stake Canada':t.nav[routes.indexOf(kind)]||t.policies[legalRoutes.indexOf(kind)];
 return `<!doctype html><html lang="${lang}-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#b4122d"><title>${esc(title)} — Treolympus</title><meta name="description" content="${esc(t.footer)}"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><link rel="alternate" hreflang="${other}-CA" href="https://www.treolympus.top${url(other,kind)}"><script type="module" src="/assets/site.js"></script>${outbound?`<meta http-equiv="refresh" content="3;url=${affiliate}">`:''}</head><body data-lang="${lang}" data-angle="${routes.includes(kind)?kind:'payments'}" ${outbound?'data-outbound="true"':''}><a class="skip" href="#main">${lang==='fr'?'Aller au contenu':'Skip to content'}</a><header class="header"><div class="wrap header-inner"><a class="brand" href="${url(lang)}" data-internal aria-label="Treolympus">${logo}</a><nav class="nav" aria-label="${lang==='fr'?'Navigation principale':'Main navigation'}">${routes.map((r,i)=>`<a href="${url(lang,r)}" data-internal ${r===kind?'aria-current="page"':''}>${t.nav[i]}</a>`).join('')}</nav><div class="header-end"><a class="language" href="${url(other,kind)}" data-internal lang="${other}" aria-label="${other==='fr'?'Lire en français':'Read in English'}">${other.toUpperCase()}</a><span class="age">19+</span></div></div></header>${body}<footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="brand" href="${url(lang)}" data-internal>${logo}</a><p>${t.footer}</p></div><div class="footer-links">${legalRoutes.map((r,i)=>`<a href="${url(lang,r)}" data-internal>${t.policies[i]}</a>`).join('')}<button data-privacy-open>${t.privacyChoice}</button></div></div><p class="ontario"><strong>${t.ontario}</strong></p><p class="legal">${t.legal}</p><div class="footer-bottom"><span>© 2026 Treolympus</span><a href="${sources.terms}" target="_blank" rel="noopener noreferrer">${t.sources} ↗</a></div></div></footer><aside class="consent" aria-label="${t.privacyChoice}" hidden><strong>${t.consent[0]}</strong><p>${t.consent[1]} <a href="${url(lang,'privacy')}">${t.policies[0]}</a></p><div><button class="btn small" data-consent="yes">${t.consent[2]}</button><button class="btn small secondary" data-consent="no">${t.consent[3]}</button></div></aside><p class="sr-only" role="status" id="privacy-status" data-saved="${t.saved}"></p></body></html>`;
}
function landing(lang,kind){
 const t=content[lang],h=t.hero[kind],focus=t.detail[kind==='home'?'payments':kind];
 return shell(lang,kind,`<main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span></span> STAKE · ${t.guide}</p><h1>${h[0]}<br><em>${h[1]}</em></h1><p class="lead">${h[2]}</p><div class="hero-actions">${cta(t)}<a class="text-link" href="#guide">${t.read}<span aria-hidden="true">↓</span></a></div><p class="micro">${t.small}</p></div><figure class="hero-art"><img src="/assets/${h[3]}.webp" width="1000" height="1000" fetchpriority="high" alt="${t.nav[routes.indexOf(h[3])]} — ${lang==='fr'?'composition éditoriale':'editorial composition'}"><figcaption><span>${t.guide}</span><strong>${h[3]==='payments'?'CAD / Interac':h[3]==='vip'?'Stake VIP':'Stake Sports'} ${arrow}</strong></figcaption></figure></section><div class="facts wrap">${t.facts.map(f=>`<div><strong>${f[0]}</strong><span>${f[1]}</span></div>`).join('')}</div><section class="section wrap" id="guide"><div class="section-head"><h2>${t.section[0]}<br><em>${t.section[1]}</em></h2><p>${t.intro}</p></div><div class="guide-grid">${t.cards.map(c=>`<article class="guide-card"><a class="card-image" href="${url(lang,c[0])}" data-internal tabindex="-1" aria-hidden="true"><img src="/assets/${c[0]}.webp" width="1000" height="1000" alt="" loading="lazy"></a><div class="card-body"><p class="eyebrow">${c[1]}</p><h3>${c[2]}</h3><p>${c[3]}</p><a class="text-link" href="${url(lang,c[0])}" data-internal>${c[4]}${arrow}</a></div></article>`).join('')}</div></section><section class="feature"><div class="wrap feature-inner"><div><p class="eyebrow">${t.guide}</p><h2>${focus[0]}</h2><p class="feature-lead">${focus[1]}</p>${cta(t)}</div><div class="steps">${focus[2].map((s,i)=>`<article><span class="step-number">0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div></article>`).join('')}</div></div></section><section class="section wrap faq"><div><p class="eyebrow">FAQ</p><h2>${t.faqTitle}</h2><p>${t.faqIntro}</p></div><div>${t.faq.map(f=>`<details><summary>${f[0]}<span aria-hidden="true">+</span></summary><p>${f[1]}</p></details>`).join('')}<p class="source-links"><a href="${sources.deposit}" target="_blank" rel="noopener noreferrer">CAD</a> · <a href="${sources.withdrawal}" target="_blank" rel="noopener noreferrer">Interac</a> · <a href="${sources.vip}" target="_blank" rel="noopener noreferrer">VIP</a></p></div></section><section class="closing wrap"><div><p class="eyebrow">STAKE · CANADA</p><h2>${t.close[0]}<br><em>${t.close[1]}</em></h2></div><div>${cta(t)}<p class="micro">${t.small}</p></div></section></main>`);
}
function policy(lang,kind){
 const t=content[lang],key=kind==='responsible-play'?'responsible':kind;
 return shell(lang,kind,`<main id="main" class="wrap policy"><a class="text-link" href="${url(lang)}" data-internal>← ${t.back}</a><p class="eyebrow">TREOLYMPUS · CANADA</p><h1>${t.policies[legalRoutes.indexOf(kind)]}</h1><p class="micro">${t.updated}</p><div class="policy-copy">${t[key].map(s=>`<section><h2>${s[0]}</h2><p>${s[1]}</p></section>`).join('')}<div class="policy-resources">${kind==='privacy'?`<button class="btn secondary" data-privacy-open>${t.privacyChoice}</button><a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel — ${t.policies[0]}</a><a href="https://propellerads.com/privacy/" target="_blank" rel="noopener noreferrer">PropellerAds — ${t.policies[0]}</a>`:`<a class="text-link" href="${sources.help}" target="_blank" rel="noopener noreferrer">${lang==='fr'?'Trouver de l’aide au Canada':'Find support in Canada'} ↗</a><a href="${sources.terms}" target="_blank" rel="noopener noreferrer">Stake — ${lang==='fr'?'conditions':'terms'}</a>`}</div></div></main>`);
}
export async function build(){
 await rm('dist',{recursive:true,force:true});await mkdir('dist/assets',{recursive:true});
 await cp('assets','dist/assets',{recursive:true});await cp('node_modules/@vercel/analytics/dist/index.mjs','dist/assets/analytics.mjs');
 for(const lang of ['en','fr']){
  for(const kind of ['home',...routes,...legalRoutes]){
   const target=kind==='home'?`dist/${lang==='fr'?'fr/':''}index.html`:`dist/${lang==='fr'?'fr/':''}${kind}.html`;
   await mkdir(path.dirname(target),{recursive:true});await writeFile(target,legalRoutes.includes(kind)?policy(lang,kind):landing(lang,kind));
  }
  for(const angle of routes){
   const t=content[lang],target=`dist/${lang==='fr'?'fr/':''}out/${angle}.html`;
   await mkdir(path.dirname(target),{recursive:true});
   await writeFile(target,shell(lang,angle,`<main id="main" class="wrap outbound"><span class="loader" aria-hidden="true"></span><h1>${t.opening[0]}</h1><p>${t.opening[1]}</p><a id="outbound-destination" class="btn" href="${affiliate}" rel="sponsored noopener">${t.opening[2]}${arrow}</a></main>`,true));
  }
 }
 await writeFile('index.html',landing('en','home'));
 await cp('robots.txt','dist/robots.txt');
 await writeFile('dist/404.html',shell('en','home','<main id="main" class="wrap outbound"><h1>Page not found.</h1><a class="btn" href="/">Back to the guide ↗</a></main>'));
}
